window.STATE =
{
  "slug": "index-3weeks-calibration",
  "dir": "2026-09-21-index-3weeks-calibration--wip",
  "title": "Расчёт индекса за 3 недели + калибровка",
  "mode": "full",
  "depth": "normal",
  "polish": null,
  "tier": null,
  "briefFile": "2026-09-21-brief.md",
  "memoryFile": "AGENTS.md",
  "skillDir": "C:/Users/1/.agents/skills/autopilot",
  "startedAt": "2026-09-21T07:56:24+03:00",
  "updatedAt": "2026-09-21T07:58:30+03:00",
  "finishedAt": null,
  "stages": [
    { "id": "preflight", "status": "done", "startedAt": "2026-09-21T07:56:24+03:00", "finishedAt": "2026-09-21T07:58:30+03:00" },
    { "id": "manifest",  "status": "done", "startedAt": "2026-09-21T07:58:30+03:00", "finishedAt": "2026-09-21T08:05:00+03:00" },
    { "id": "briefing",  "status": "skipped", "note": "полный автомат — самобрифинг, решения A1–A5 в manifest.md" },
    { "id": "spec",      "status": "done", "startedAt": "2026-09-21T08:05:00+03:00", "finishedAt": "2026-09-21T08:20:00+03:00" },
    { "id": "plan",      "status": "done", "startedAt": "2026-09-21T08:20:00+03:00", "finishedAt": "2026-09-21T08:35:00+03:00", "note": "ярус T2 — 4 таска в 3 волны: 1 (01), 2 (02, 03 параллельно), 3 (04)" },
    { "id": "build",     "status": "active", "startedAt": "2026-09-21T08:35:00+03:00" },
    { "id": "review",    "status": "pending" },
    { "id": "final",     "status": "pending" }
  ],
  "requirements": {
    "total": 9, "done": 6, "inTicket": 1, "inSpec": 0,
    "placeholder": 0, "deferred": 2, "dropped": 0
  },
  "tickets": [
    { "id": "01", "title": "Расчётное ядро пайплайна", "requirements": ["R01", "R04i", "R07i"],
      "blockedBy": [], "wave": 1, "zone": ["calc/engine.js", "calc/params.js", "tests/calc-engine.test.js"],
      "status": "done", "startedAt": "2026-09-21T08:07:06+03:00", "finishedAt": "2026-09-21T08:32:15+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["calc/engine.js", "calc/params.js", "tests/calc-engine.test.js"],
      "tests": { "passed": 147, "failed": 0 },
      "commit": "fac8e03",
      "concerns": ["engine.js:201 — q для null-драйверов берёт c по умолчанию medium (0.7), зафиксировать при калибровке", "имя round1 против Math.round; мёртвая ветка Д9.6b; дефолты engine дублируют params (аккуратно при смене k); тест 30%-лимита только неравенствами; причина override нестрого; d8Strength избыточная проверка"] },
    { "id": "02", "title": "Входные сигналы трёх недель", "requirements": ["R02", "R05i"],
      "blockedBy": ["01"], "wave": 2, "zone": ["calc/input/"],
      "status": "done", "startedAt": "2026-09-21T08:33:00+03:00", "finishedAt": "2026-09-21T09:10:00+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["calc/input/2026-08-30.json", "calc/input/2026-09-06.json", "calc/input/2026-09-13.json"],
      "tests": { "passed": 147, "failed": 0 },
      "commit": "a28292c",
      "concerns": ["D01: наблюдения трёх снапшотов идентичны без дат — недельная динамика только через инерцию/покрытие", "даты источников вне окна through (системное отставание демо-данных)", "Д9 medium при пустом Д9 занижает 1−q — правило зафиксировать"] },
    { "id": "03", "title": "Якорные сценарии и калибровка", "requirements": ["R03", "R06i", "R09i"],
      "blockedBy": ["01"], "wave": 2, "zone": ["calc/input/anchors/", "calc/calibrate.js", "docs/calibration-journal.md"],
      "status": "done", "startedAt": "2026-09-21T08:33:00+03:00", "finishedAt": "2026-09-21T09:10:00+03:00",
      "retries": 0, "repairs": 0, "handoffs": 0,
      "files": ["calc/input/anchors/", "calc/calibrate.js", "docs/calibration-journal.md", "calc/params.js", "calc/engine.js", "tests/calibrate.test.js", "tests/calc-engine.test.js"],
      "tests": { "passed": 150, "failed": 0 },
      "commit": "276f360",
      "concerns": ["журнал: I_agg proxy-sanctions 0.132 не бьётся с индексом 32 (≈0.163) — попадания сохраняются", "verify Карибского-1962 нарушает строгую хронологию rolling-origin (намеренно, защита от подгонки)", "журнал marginOf считает index−lo, не min двусторонний; «без лимита ~99.9» не сходится с прогоном", "tie-break ветка selectK без теста; main() дублирует логику попадания", "cuban-1962: D5.1–D5.3 = 1 при отсутствии киберсферы — трактовать D5 как инфо-измерение эпохи", "buildDrivers живёт в calibrate.js — таск 04 переиспользует, не дублирует"] },
    { "id": "04", "title": "Пересчёт трёх недель в data/ и выкатная обвязка", "requirements": ["R02", "R01"],
      "blockedBy": ["01", "02", "03"], "wave": 3, "zone": ["calc/calc.js", "data/2026-08-30/", "data/2026-09-06/", "data/2026-09-13/"],
      "status": "in-progress", "startedAt": "2026-09-21T09:16:32+03:00", "retries": 0, "repairs": 0, "handoffs": 0 }
  ],
  "singlePass": null,
  "tests": null,
  "debt": { "placeholders": [], "assumptions": [], "emptyEnv": [] },
  "additions": [],
  "coverage": { "missing": 0, "half": 0, "extra": 9, "disposition": "все extras — R##.n-углубления или R##i-подразумеваемые из манифеста; перезапись значений 3 недель — суть R02 (пересчёт), зафиксировано в spec Решение 5/8" },
  "concerns": [
    "spec-ревью таса 01: снапшот параметров во входном файле — путь на params.js, не инлайн-копия; при смене params старые входы пересчитаются новыми числами — оговорка обязана попасть в журнал калибровки (таск 03)",
    "spec-ревью таса 01: дефолт c=0.7 для null-драйверов в знаменателе q — зафиксировать в журнале калибровки",
    "craft таса 01 (не блокируют): round1; мёртвая ветка Д9.6b; дефолты engine дублируют params.js — при смене k в таске 03 синхронизировать; тест лимита 30 % только неравенствами; причина override нестрогая; d8Strength избыточная проверка"
  ],
  "reviewers": { "manifestSpec": "agent-44", "craft": "agent-45" },
  "blind": null
}
